### PR TITLE
Migrate `node_helpers` code from private `robot` monorepo

### PR DESCRIPTION
**Pull request by apockill**
This is the first **big drop**, and includes the work that has been done over the past 3 years on the internal Urban Machine monorepo. Some things maybe buggy, because there had to be modifications to the code to rip apart dependencies on the monorepo.

Expect a few fixes in the coming weeks.

### CODE REVIEW

**Comment by agillies8** [comment]
👀

**Comment by apockill** [comment]
@agillies8 I still have 182 files left to migrate on my machine :sweat_smile:

**Comment by agillies8** [comment]
yikes!

**Comment by apockill** [comment]
Okay, this is close enough to merge to main. Next PR's will flesh out CI, fix remaining broken tests, and make some example nodes!

**Pull request merged**
